version: '3'
services:
  db:
    image: mysql:latest # use latest version of mysql
    restart: always
    environment: # add default values, see docs for more info.
      MYSQL_USER: user_prod
      MYSQL_ROOT_PASSWORD: mypassword_prod
      MYSQL_PASSWORD: mypassword_prod
      MYSQL_DATABASE: air_manager_db_prod # create this database on startup
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - backend-network
    healthcheck:
      test: "/usr/bin/mysql --user=user_prod --password=mypassword_prod --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
