spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: ${INIT_MODE}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: ${DDL_AUTO_MODE}
    properties:
      hibernate:
        show_sql: false
        format_sql: false

      javax:
        persistence:
          validation:
            mode: none

server:
  port: ${PORT}